// <auto-generated />
using System;
using DriverTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriverTrack.Infrastructure.Migrations
{
    [DbContext(typeof(DriverTrackDbContext))]
    partial class DriverTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DriverTrack.Domain.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.FuelEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DistanceSinceLastRefuel")
                        .HasColumnType("REAL");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsFullTank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<double>("Liters")
                        .HasColumnType("REAL");

                    b.Property<double>("OdometerReading")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Date");

                    b.HasIndex("VehicleId", "Date");

                    b.ToTable("FuelEntries");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.RouteEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Earnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EndOdometer")
                        .HasColumnType("REAL");

                    b.Property<double?>("FuelUsed")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RouteTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("StartOdometer")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalDistance")
                        .HasColumnType("REAL");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouteTypeId");

                    b.HasIndex("DriverId", "StartDate");

                    b.HasIndex("VehicleId", "StartDate");

                    b.ToTable("RouteEntries");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.RouteType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Earnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AverageFuelConsumption")
                        .HasColumnType("REAL");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("Brand", "Model");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.FuelEntry", b =>
                {
                    b.HasOne("DriverTrack.Domain.Entities.Driver", "Driver")
                        .WithMany("FuelEntries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverTrack.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("FuelEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.RouteEntry", b =>
                {
                    b.HasOne("DriverTrack.Domain.Entities.Driver", "Driver")
                        .WithMany("RouteEntries")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverTrack.Domain.Entities.RouteType", "RouteType")
                        .WithMany("RouteEntries")
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverTrack.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("RouteEntries")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("RouteType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("DriverTrack.Domain.Entities.Driver", "Driver")
                        .WithMany("Vehicles")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.Driver", b =>
                {
                    b.Navigation("FuelEntries");

                    b.Navigation("RouteEntries");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.RouteType", b =>
                {
                    b.Navigation("RouteEntries");
                });

            modelBuilder.Entity("DriverTrack.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("FuelEntries");

                    b.Navigation("RouteEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
